Repository smartlyio/github-actions, pull requests merged in 2023-08, with the labels that each got.

#24 Exclude alpha tags in version calculation
  get-next-semantic-version/action.yml
Labels: patch

#25 feat: new action publish-confluence
  README.md
  publish-confluence/Dockerfile
  publish-confluence/LICENSE
  publish-confluence/README.md
  publish-confluence/action.yml
Labels: major

#26 Publish confluence
  publish-confluence/Dockerfile
  publish-confluence/action.yml
Labels: minor
