Repository smartlyio/github-actions, pull requests merged in 2025-04, with the labels that each got.

#42 Release action-validator, actionlint and shellcheck
  action-validator/action.yml
  actionlint/action.yml
  shellcheck/action.yml
Labels: major

#43 Improve ShellCheck action
  shellcheck/action.yml
Labels: patch

#44 Bump publish-confluence to latest
  publish-confluence/Dockerfile
Labels: minor
